spring.application.name=api

logging.file.name=spring.log
# Liga a interface web do banco de dados
spring.h2.console.enabled=true

# Dá um endereço fixo para o banco (neobankdb)
spring.datasource.url=jdbc:h2:mem:neobankdb
spring.datasource.username=sa
spring.datasource.password=